# Translation workflow is:
# 1. English I18N keys/captions changed on master
# 2. master merged to transifex-synchronization-source
# 3. Transifex picks up changes on transifex-synchronization-source
# 4. Translations made on Transifex
# 5. Transifex creates pull request against transifex-synchronization-source

# Since transifex-synchronization-source is just a staging branch to
# control updates to Transifex, it is never merged to master, so we
# need to change the merge target of Transifex's pull requests to master
name: Merge translations to master

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_change_base_branch:
    if: github.event.pull_request.base.ref == 'transifex-synchronization-source'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout base branch
      uses: actions/checkout@v4
      with:
        ref: 'refs/heads/master'

    - name: Setup Git User
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
      
    - name: Change base branch
      run: |
        git push origin HEAD:${{ github.event.pull_request.base.ref }}
